apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tbt-ratio-controller.fullname" . }}-rustatio-config
  labels:
    {{- include "tbt-ratio-controller.labels" . | nindent 4 }}
data:
  rustatio-randomness.json: |
{{ .Values.rustatioConfig | toJson | indent 4 }}
