apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tbt-ratio-controller.fullname" . }}-secret
  labels:
    {{- include "tbt-ratio-controller.labels" . | nindent 4 }}
type: Opaque
data:
  rustatio-auth-token: {{ .Values.secrets.rustatioAuthToken | b64enc | quote }}
